### ISSUE TITLE
是否可以在linux下使用？ Can it be used under Linux

### ISSUE THREAD

**Issue by yangjieshao** [ReferenceType/H264Sharp#1]
Can it be used under Linux??

**Comment by ReferenceType** [comment]
Not yet. But i will provide support.

if you want to compile for linux yourself you have to do some modifications.
- Currently im using  ```HMODULE hDll = LoadLibrary(dllname)```  to load cisco dlls. You have to change it to linux version.
- Im using ppl.h,  on ConverterLocal.cpp you have to either remove parallelisation or implement openmp version.
- if your linux machine doesnt run on x86-64, you have to disable SSE on converter (it uses emmintrin.h ).
- finally change cisco dll to linux distro version (linux doesnt use dll it uses .so)

**Comment by yangjieshao** [comment]
thanks

**Comment by ReferenceType** [comment]
it is now supported for Linux.
