### ISSUE TITLE
How to decode h264 bare stream?

### ISSUE THREAD

**Issue by xlievo** [ReferenceType/H264Sharp#2]
Such as { 0, 0, 0, 1, ... } begins with data.
Might it be used like this?
```C#
foreach (var group in groupedArrays)
{
    var d = group.ToArray();
    var rgb = new RgbImage(768, 1920);
    if (decoder.Decode(d, 0, d.Length, noDelay: true, out DecodingState ds, ref rgb))
    {

    }
}
```

**Comment by ReferenceType** [comment]
Assuming you are using single layer on encoder;
you can do one by one for each element, or you can merge them into single array. I personally combine them into single.

I need to demistify one thing,

- groupedArrays (EncodedData[]) contains 2 elements if the frame is IDR frame, the first one is something fixed, (like 28 bytes), which is the metadata about the encoder. Without this DecodingState  will tell you dsNoParamSets.
- If you decode this 28 bytes there wont be any image on the output(dsErrorFree and method returns false). Image appears when you also decode the following data.
- If you merge them into single array and decode, you will get the image in one shot.
- For frames that is not IDR, this array contains single element.

Multi layer encoder where you have multiple streams is something different, and I haven't used it and it may require separate decoding for each stream. In any case the multi layer data will appear on the  (EncodedData[]) and each index marks the layer number. Its mapped from Cisco implementation directly and in this case please check the openh264 repo of the cisco(search on issues).

**Comment by xlievo** [comment]
Roughly understand the H264 stream coding
I try, thank you for your answer!
