### ISSUE TITLE
Is it possible to release Android and IOS versions?

### ISSUE THREAD

**Issue by xlievo** [ReferenceType/H264Sharp#4]
```CS
#elif OS_ANDROID_ARM
        public const string CiscoDllName64bit = "./libopenh264-2.4.1-android-arm64.7.so";
        public const string CiscoDllName32bit = "./libopenh264-2.4.1-android-arm.7.so";
        
        public const string WrapperDllName64bit = "H264SharpNative-android-arm64.7.so";
        public const string WrapperDllName32bit = "H264SharpNative-android-arm.7.so";
#elif OS_ANDROID_X86
        public const string CiscoDllName64bit = "./libopenh264-2.4.1-android-x64.7.so";
        public const string CiscoDllName32bit = "./libopenh264-2.4.1-android-x86.7.so";
        
        public const string WrapperDllName64bit = "H264SharpNative-android-x64.7.so";
        public const string WrapperDllName32bit = "H264SharpNative-android-x86.7.so";
#elif OS_IOS
        public const string CiscoDllName64bit = "./libopenh264-2.4.1-ios.a";
        public const string WrapperDllName64bit = "H264SharpNative-ios.a";
#endif
```

**Comment by xlievo** [comment]
Shut it down until someone brings it up again.

**Comment by ReferenceType** [comment]
I will do it, currently I'm quite busy with the work, cant find the time or energy on weekends.
But it will come soon.

**Comment by xlievo** [comment]
Thanks for your efforts, it has amazing YUV <> RGB performance compared to other packaging libraries!
There is a small issue that does not affect, the memory is not very stable, the fluctuation is relatively large, compared to other libraries, but YUV <> RGB performance is better enough.
Looking forward to the early arrival of mobile support, there should be no problem, the upstream has released a mobile version.

**Comment by ReferenceType** [comment]
hi can you show me briefly how are you using it?
it shouldn't have any fluctuations.  Its designed to cycle same memory.

**Comment by xlievo** [comment]
When I call the library decoding in the following way, there will be a few relatively small fluctuations in memory, I am not sure where the problem is, but by intuition and Yuv420P2RGB related, but does not affect, perhaps normal fluctuations.
```C#
decoder = new H264Decoder();
decoder.Initialize();

static bool DecodeNal(ArraySegment<byte> nal, out RGBImage image)
{
    if (manage.decoder.Decode([.. nal], 0, nal.Count, noDelay: true, out _, out RGBImagePointer rgb))
    {
        var bytes = arrayPool.Rent(rgb.Stride * rgb.Height);
        rgb.CopyTo(bytes, 0);
        image = new RGBImage((ushort)rgb.Width, (ushort)rgb.Height, bytes, nal.Count);
        return true;
    }

    image = default;
    return false;
}
```

When I P/Invoke other openh264 wrapper libraries, the memory is very stable, basically no change.
```C#
public static unsafe bool Decode(byte[] encoded, int count, out RGBImage img)
{
    fixed (byte* pEncoded = encoded)
    {
        var packet = new IntPtr(pEncoded);
        var packetLen = (uint)count;
        var decodeType = DecodeType.BGR8;

        var decodedData = decoder_decode_rgb(manage.decoder2, packet, packetLen, decodeType);

        if (IntPtr.Zero != decodedData.data)
        {
            var bytes = arrayPool.Rent((int)decodedData.len);
            Marshal.Copy(decodedData.data, bytes, 0, (int)decodedData.len);
            img = new RGBImage((ushort)decodedData.width, (ushort)decodedData.height, bytes, count);

            decoder_rgb_free(decodedData.data, decodedData.len);
            return true;
        }

        img = default;
        return false;
    }
}
```

Maybe it's not worth your investigation and you should focus on mobile platform support?  :)

**Comment by ReferenceType** [comment]
Hi again thanks for sharing, I will give some explanation, sorry about its length.
So I want to point out:
Decoder has two ways of decoding:
 - one is with the `out RGBImagePointer rgb` which is a ref struct on purpose. On unmanaged side, It writes the decoded bytes in Cached array, and it reuses same array in consecutive decodes, so what you get is only a reference to that memory. so not intended for storage, but handling decoded image ephemerally.
 - second one is with `ref RgbImage img` which receives the memory from managed side and directly decodes there without copy. When you create new instance of RgbImage it allocates the raw image array. This object is storable, and If you are going to use this you should either use same reference or pool these objects. One should avoid making new on each decode
 
Yuv<>Rgb converter does not allocate any memory its either uses the memory provided by managed side or the cached array inside the unmanaged side depending on which method is called, as I explained above

Similarly encoder also gives a reference object to unmanaged cached memory which is again cycled through each encode operation.
It doesn't allocate any memory unless you call .GetBytes() method of the Encoded data.

and a tip, Encoded data which consists arrays of byte arrays can be stitched(copy to) into single contiguous array and fed into decoder as single input, If you are only using single layer(standard use case).

**Comment by xlievo** [comment]
Thank you for your answer, after a simple browse of the library source code, fully agree with you.
You also mentioned merging multiple NAL cells to pass as a contiguous array, I will try! Here's to a good library! Again, look forward to mobile platform support.
